spring:
  profiles: mysqldev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:32778/oauth?autoReconnect=true
    username: root
    password: root
    #    initialization-mode: always
    #    data: /data.sql
    poolName: SpringBootHikariCP
    maximumPoolSize: 5
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000
  redis:
    host: localhost
    port: 32775
    max-total: 128
    max-idle: 128
    min-idle: 16
    min-evictable-idle-time-millis: 60
    time-between-eviction-runs-millis: 30
    block-when-exhausted: true
    use-pool: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #  flyway:
    #    url: jdbc:mysql://localhost:32769/mysql
    #    schemas: oauth
    #    user: root
    #    password: root
  security:
    oauth2:
      resource:
        filter-order: 3
oauth2:
  clientId: tester
  clientSecret: tester
  tokenExpired: 480
  refreshToken: 480
---
spring:
  profiles: development
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:2600/midware_master_db?autoReconnect=true
    #    driverClassName: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://localhost:32769/oauth?autoReconnect=true
    username: root
    #    password: root
    password: P@ssw0rd.15!
    poolName: SpringBootHikariCP
    maximumPoolSize: 5
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000
  redis:
    host: localhost
    port: 32775
    max-total: 128
    max-idle: 128
    min-idle: 16
    min-evictable-idle-time-millis: 60
    time-between-eviction-runs-millis: 30
    block-when-exhausted: true
    use-pool: true
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #  flyway:
  #    url: jdbc:mysql://localhost:32769/mysql
  #    schemas: oauth
  #    user: root
  #    password: root
  security:
    oauth2:
      resource:
        filter-order: 3
oauth2:
  clientId: tester
  clientSecret: tester
  tokenExpired: 480
  refreshToken: 480




