spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:2600/midware_master_db?autoReconnect=true
    username: root
    password: P@ssw0rd.15!
  redis:
    host: localhost
    port: 32770
    max-total: 128
    max-idle: 128
    min-idle: 16
    min-evictable-idle-time-millis: 60
    time-between-eviction-runs-millis: 30
    block-when-exhausted: true
    use-pool: true
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  security:
    oauth2:
      resource:
        filter-order: 3
oauth2:
  url: http://localhost:8080/oauth/token
  clientId: tester
  clientSecret: tester
  tokenExpired: 60
  refreshToken: 345



